# PIM

pim_datagrid:
    resource: "@PimDataGridBundle/Resources/config/routing.yml"

pim_dashboard:
    resource: "@PimDashboardBundle/Resources/config/routing.yml"

pim_enrich:
    resource: "@PimEnrichBundle/Resources/config/routing.yml"

pim_ui:
    resource: "@PimUIBundle/Resources/config/routing.yml"

pim_user:
    resource: "@PimUserBundle/Resources/config/routing.yml"

pim_importexport:
    resource: "@PimImportExportBundle/Resources/config/routing.yml"

pim_webservice:
    resource: "@PimWebServiceBundle/Resources/config/routing.yml"

pim_comment:
    resource: "@PimCommentBundle/Resources/config/routing.yml"

pim_pdf_generator:
    resource: "@PimPdfGeneratorBundle/Resources/config/routing.yml"

pim_notification:
    resource: "@PimNotificationBundle/Resources/config/routing.yml"

pim_reference_data:
    resource: "@PimReferenceDataBundle/Resources/config/routing.yml"

pim_inner_variation_inner_variation_type:
    resource: '@PimInnerVariationBundle/Resources/config/routing/inner_variation_type.yml'
    prefix: /configuration/inner_variation_type

# Oro platform

oro_default:
    pattern:  /
    defaults:
        template:    PimDashboardBundle:Dashboard:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_auto_routing:
    resource: .
    type:     oro_auto

# other third party

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"
