extensions:
    product-edit-form:
        module: pim/product-edit-form

    cache-invalidator:
        module: pim/product-edit-form/cache-invalidator
        parent: product-edit-form
        position: 100

    sequential-edit:
        module: pim/product-edit-form/sequential-edit
        parent: product-edit-form
        targetZone: sequential
        aclResourceId: pim_enrich_product_edit_attributes
        position: 100

    form-tabs:
        module: pim/product-edit-form/form-tabs
        parent: product-edit-form
        targetZone: content
        position: 100

    product-label:
        module: pim/product-edit-form/product-label
        parent: product-edit-form
        targetZone: title
        position: 100

    back-to-grid:
        module: pim/product-edit-form/back-to-grid
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_index
        position: 80

    download-pdf:
        module: pim/product-edit-form/download-pdf
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_pdf_generator_product_download
        position: 90

    delete:
        module: pim/product-edit-form/delete
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_remove
        position: 100

    status-switcher:
        module: pim/product-edit-form/status-switcher
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_change_state
        position: 110

    save-buttons:
        module: pim/product-edit-form/save-buttons
        parent: product-edit-form
        targetZone: buttons
        position: 120

    save:
        module: pim/product-edit-form/save
        parent: product-edit-form
        targetZone: buttons
        position: 0

    save-and-back:
        module: pim/product-edit-form/save-and-back
        parent: product-edit-form
        targetZone: buttons
        position: 0

    state:
        module: pim/product-edit-form/state
        parent: product-edit-form
        targetZone: state
        position: 900

    family:
        module: pim/product-edit-form/meta/family
        parent: product-edit-form
        targetZone: meta
        position: 80

    change-family:
        module: pim/product-edit-form/meta/change-family
        parent: family
        targetZone: self
        aclResourceId: pim_enrich_product_change_family
        position: 100

    created:
        module: pim/product-edit-form/meta/created
        parent: product-edit-form
        targetZone: meta
        position: 90

    updated:
        module: pim/product-edit-form/meta/updated
        parent: product-edit-form
        targetZone: meta
        position: 100

    groups:
        module: pim/product-edit-form/meta/groups
        parent: product-edit-form
        targetZone: meta
        position: 110

    attributes:
        module: pim/product-edit-form/attributes
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_edit_attributes
        position: 90

    categories:
        module: pim/product-edit-form/categories
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_categories_view
        position: 100

    associations:
        module: pim/product-edit-form/associations
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_associations_view
        position: 110

    panels:
        module: pim/product-edit-form/panel/panels
        parent: form-tabs
        targetZone: panels
        position: 100

    attribute-group-selector:
        module: pim/product-edit-form/attributes/attribute-group-selector
        parent: attributes
        targetZone: sidebar
        position: 100

    add-attribute:
        module: pim/product-edit-form/attributes/add-attribute
        parent: attributes
        targetZone: other-actions
        aclResourceId: pim_enrich_product_add_attribute
        position: 90

    copy:
        module: pim/product-edit-form/attributes/copy
        parent: attributes
        targetZone: header
        position: 100

    scope-switcher:
        module: pim/product-edit-form/scope-switcher
        parent: attributes
        targetZone: context-selectors
        position: 100

    locale-switcher:
        module: pim/product-edit-form/locale-switcher
        parent: attributes
        targetZone: context-selectors
        position: 110

    validation:
        module: pim/product-edit-form/attributes/validation
        parent: attributes
        targetZone: header
        position: 100

    variant-group:
        module: pim/product-edit-form/attributes/variant-group
        parent: attributes
        targetZone: self
        position: 100

    completeness:
        parent: panels
        module: pim/product-edit-form/panel/completeness
        targetZone: panel-content
        position: 100

    comments:
        parent: panels
        module: pim/product-edit-form/panel/comments
        targetZone: panel-content
        aclResourceId: pim_enrich_product_comment
        position: 110

    history:
        parent: panels
        module: pim/product-edit-form/panel/history
        targetZone: panel-content
        aclResourceId: pim_enrich_product_history
        position: 120

    selector:
        parent: panels
        module: pim/product-edit-form/panel/selector
        position: 100

    copy-scope-switcher:
        module: pim/product-edit-form/scope-switcher
        parent: copy
        targetZone: context-selectors
        position: 100

    copy-locale-switcher:
        module: pim/product-edit-form/locale-switcher
        parent: copy
        targetZone: context-selectors
        position: 110

attribute_fields:
    akeneo-switch-field:           pim/boolean-field
    akeneo-datepicker-field:       pim/date-field
    akeneo-media-uploader-field:   pim/media-field
    akeneo-metric-field:           pim/metric-field
    akeneo-multi-select-field:     pim/multi-select-field
    akeneo-number-field:           pim/number-field
    akeneo-price-collection-field: pim/price-collection-field
    akeneo-simple-select-field:    pim/simple-select-field
    akeneo-text-field:             pim/text-field
    akeneo-textarea-field:         pim/textarea-field
    akeneo-wysiwyg-field:          pim/wysiwyg-field
